application: rateawatch 
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css 

- url: /js
  static_dir: js 

- url: /images
  static_dir: images 

- url: /static-data
  static_dir: static-data

- url: /.*
  script: rateawatch.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
