application: watchapp 
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css 

- url: /static-data
  static_dir: static-data

- url: /.*
  script: watchapp.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
